// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pizzeria_Toscana.Models;

#nullable disable

namespace Pizzeria_Toscana.Migrations
{
    [DbContext(typeof(PizzerieContext))]
    [Migration("20250303120023_ingredientLink")]
    partial class ingredientLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Pizzeria_Toscana.Models.Categorie", b =>
                {
                    b.Property<int>("ID_Categorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Categorie"));

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID_Categorie");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("Pizzeria_Toscana.Models.Comanda", b =>
                {
                    b.Property<int>("NR_Comanda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NR_Comanda"));

                    b.Property<int?>("CosID_Cos")
                        .HasColumnType("int");

                    b.Property<string>("Descriere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("Suma")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NR_Comanda");

                    b.HasIndex("CosID_Cos");

                    b.HasIndex("UserId");

                    b.ToTable("Comenzi");
                });

            modelBuilder.Entity("Pizzeria_Toscana.Models.Comanda_Produs", b =>
                {
                    b.Property<int>("ID_Comanda_Produs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Comanda_Produs"));

                    b.Property<int>("ComandaId")
                        .HasColumnType("int");

                    b.Property<string>("ProdusId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID_Comanda_Produs");

                    b.HasIndex("ComandaId");

                    b.HasIndex("ProdusId");

                    b.ToTable("Comanda_Produs");
                });

            modelBuilder.Entity("Pizzeria_Toscana.Models.Cos", b =>
                {
                    b.Property<int>("ID_Cos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Cos"));

                    b.Property<string>("ID_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pret_total")
                        .HasColumnType("int");

                    b.HasKey("ID_Cos");

                    b.ToTable("Cos");
                });

            modelBuilder.Entity("Pizzeria_Toscana.Models.Cos_Produs", b =>
                {
                    b.Property<int>("ID_CosProdus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_CosProdus"));

                    b.Property<string>("COD_Produs")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cantitate")
                        .HasColumnType("int");

                    b.Property<int>("ID_Cos")
                        .HasColumnType("int");

                    b.Property<int>("Pret")
                        .HasColumnType("int");

                    b.HasKey("ID_CosProdus");

                    b.HasIndex("COD_Produs");

                    b.HasIndex("ID_Cos");

                    b.ToTable("Cos_Produs");
                });

            modelBuilder.Entity("Pizzeria_Toscana.Models.Ingredient", b =>
                {
                    b.Property<int>("COD_Ingredient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("COD_Ingredient"));

                    b.Property<string>("Denumire")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("COD_Ingredient");

                    b.ToTable("Ingrediente");
                });

            modelBuilder.Entity("Pizzeria_Toscana.Models.Produs", b =>
                {
                    b.Property<string>("COD_Produs")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Denumire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descriere")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ID_Categorie")
                        .HasColumnType("int");

                    b.Property<int>("Pret")
                        .HasColumnType("int");

                    b.Property<byte[]>("ProdusPicture")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("COD_Produs");

                    b.HasIndex("ID_Categorie");

                    b.ToTable("Produse");
                });

            modelBuilder.Entity("Pizzeria_Toscana.Models.Produs_Ingredient", b =>
                {
                    b.Property<int>("COD_Produs_Ingredient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("COD_Produs_Ingredient"));

                    b.Property<int>("COD_Ingredient")
                        .HasColumnType("int");

                    b.Property<string>("COD_Produs")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cantitate_Ingredient")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("COD_Produs_Ingredient");

                    b.HasIndex("COD_Ingredient");

                    b.HasIndex("COD_Produs");

                    b.ToTable("Produs_Ingredient");
                });

            modelBuilder.Entity("Pizzeria_Toscana.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CosID_Cos")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Prenume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CosID_Cos");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Pizzeria_Toscana.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Pizzeria_Toscana.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pizzeria_Toscana.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Pizzeria_Toscana.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pizzeria_Toscana.Models.Comanda", b =>
                {
                    b.HasOne("Pizzeria_Toscana.Models.Cos", "Cos")
                        .WithMany("Comanda")
                        .HasForeignKey("CosID_Cos");

                    b.HasOne("Pizzeria_Toscana.Models.User", "User")
                        .WithMany("Comanda")
                        .HasForeignKey("UserId");

                    b.Navigation("Cos");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pizzeria_Toscana.Models.Comanda_Produs", b =>
                {
                    b.HasOne("Pizzeria_Toscana.Models.Comanda", "Comanda")
                        .WithMany("Comanda_Produs")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pizzeria_Toscana.Models.Produs", "Produs")
                        .WithMany("Comanda_Produs")
                        .HasForeignKey("ProdusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Comanda");

                    b.Navigation("Produs");
                });

            modelBuilder.Entity("Pizzeria_Toscana.Models.Cos_Produs", b =>
                {
                    b.HasOne("Pizzeria_Toscana.Models.Produs", "Produs")
                        .WithMany("CosProdus")
                        .HasForeignKey("COD_Produs")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pizzeria_Toscana.Models.Cos", "Cos")
                        .WithMany("CosProdus")
                        .HasForeignKey("ID_Cos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cos");

                    b.Navigation("Produs");
                });

            modelBuilder.Entity("Pizzeria_Toscana.Models.Produs", b =>
                {
                    b.HasOne("Pizzeria_Toscana.Models.Categorie", "Categorie")
                        .WithMany("Produse")
                        .HasForeignKey("ID_Categorie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("Pizzeria_Toscana.Models.Produs_Ingredient", b =>
                {
                    b.HasOne("Pizzeria_Toscana.Models.Ingredient", "Ingredient")
                        .WithMany("Produs_Ingredient")
                        .HasForeignKey("COD_Ingredient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pizzeria_Toscana.Models.Produs", "Produs")
                        .WithMany("Produs_Ingredient")
                        .HasForeignKey("COD_Produs")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Ingredient");

                    b.Navigation("Produs");
                });

            modelBuilder.Entity("Pizzeria_Toscana.Models.User", b =>
                {
                    b.HasOne("Pizzeria_Toscana.Models.Cos", "Cos")
                        .WithMany()
                        .HasForeignKey("CosID_Cos");

                    b.Navigation("Cos");
                });

            modelBuilder.Entity("Pizzeria_Toscana.Models.Categorie", b =>
                {
                    b.Navigation("Produse");
                });

            modelBuilder.Entity("Pizzeria_Toscana.Models.Comanda", b =>
                {
                    b.Navigation("Comanda_Produs");
                });

            modelBuilder.Entity("Pizzeria_Toscana.Models.Cos", b =>
                {
                    b.Navigation("Comanda");

                    b.Navigation("CosProdus");
                });

            modelBuilder.Entity("Pizzeria_Toscana.Models.Ingredient", b =>
                {
                    b.Navigation("Produs_Ingredient");
                });

            modelBuilder.Entity("Pizzeria_Toscana.Models.Produs", b =>
                {
                    b.Navigation("Comanda_Produs");

                    b.Navigation("CosProdus");

                    b.Navigation("Produs_Ingredient");
                });

            modelBuilder.Entity("Pizzeria_Toscana.Models.User", b =>
                {
                    b.Navigation("Comanda");
                });
#pragma warning restore 612, 618
        }
    }
}
